VIA_ENABLE = yes
VIAL_ENABLE = yes
LT0_ENABLE = yes

QMK_SETTINGS = no
TAP_DANCE_ENABLE = no
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no

CONSOLE_ENABLE = no
COMMAND_ENABLE = no

BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes

VIAL_ENCODERS_ENABLE = no

VIAL_INSECURE = yes
